In [41]:
import numpy as np
import math

# Generating Data
hydrophone1 = [0, 0, 0]
hydrophone2 = [-0.20, 0, 0.15]
hydrophone3 = [-0.25, 0.15, -0.15]
hydrophone4 = [0.20, -0.15, 0.05]

pinger_location = [1.9, -1.1, 0.6]

time_1 = math.sqrt( (hydrophone1[0] - pinger_location[0])**2 + (hydrophone1[1] - pinger_location[1])**2 + (hydrophone1[2] - pinger_location[2])**2 ) / 1480
time_2 = math.sqrt( (hydrophone2[0] - pinger_location[0])**2 + (hydrophone2[1] - pinger_location[1])**2 + (hydrophone2[2] - pinger_location[2])**2 ) / 1480
time_3 = math.sqrt( (hydrophone3[0] - pinger_location[0])**2 + (hydrophone3[1] - pinger_location[1])**2 + (hydrophone3[2] - pinger_location[2])**2 ) / 1480
time_4 = math.sqrt( (hydrophone4[0] - pinger_location[0])**2 + (hydrophone4[1] - pinger_location[1])**2 + (hydrophone4[2] - pinger_location[2])**2 ) / 1480

print(time_1)
print(time_2)
print(time_3)
print(time_4)
print("\n")
print(time_1 - time_2)
print(time_1 - time_3)
print(time_1 - time_4)

0.0015378117130731138
0.00163039574486671
0.0017551317848460187
0.0013673044827600042


-9.258403179359612e-05
-0.0002173200717729049
0.0001705072303131096


In [42]:
distance_2 = (time_1 - time_2) * 1480
distance_3 = (time_1 - time_3) * 1480
distance_4 = (time_1 - time_4) * 1480

main_vector = [
    hydrophone2,
    hydrophone3,
    hydrophone4
]

distance_vector = [
    [distance_2],
    [distance_3],
    [distance_4]
]

main_vector = np.array(main_vector)
distance_vector = np.array(distance_vector)
inverse_main_vector = np.linalg.inv(main_vector)

result = np.matmul(inverse_main_vector, distance_vector)

print(main_vector)
print(distance_vector)
print(inverse_main_vector)
print(result)

[[-0.2   0.    0.15]
 [-0.25  0.15 -0.15]
 [ 0.2  -0.15  0.05]]
[[-0.13702437]
 [-0.32163371]
 [ 0.2523507 ]]
[[ -3.63636364  -5.45454545  -5.45454545]
 [ -4.24242424  -9.6969697  -16.36363636]
 [  1.81818182  -7.27272727  -7.27272727]]
[[ 0.87617773]
 [-0.42918731]
 [ 0.25474119]]
