In [32]:
import numpy as np
import math

# Generating Data
hydrophone1 = [0.20, 0.15, -0.15]
hydrophone2 = [-0.20, 0.00, 0.15]
hydrophone3 = [-0.25, 0.15, -0.15]
hydrophone4 = [0.20, -0.15, 0.05]

pinger_location = [-5, -10, -18]

time_1 = math.sqrt( (hydrophone1[0] - pinger_location[0])**2 + (hydrophone1[1] - pinger_location[1])**2 + (hydrophone1[2] - pinger_location[2])**2 ) / 1500
time_2 = math.sqrt( (hydrophone2[0] - pinger_location[0])**2 + (hydrophone2[1] - pinger_location[1])**2 + (hydrophone2[2] - pinger_location[2])**2 ) / 1500
time_3 = math.sqrt( (hydrophone3[0] - pinger_location[0])**2 + (hydrophone3[1] - pinger_location[1])**2 + (hydrophone3[2] - pinger_location[2])**2 ) / 1500
time_4 = math.sqrt( (hydrophone4[0] - pinger_location[0])**2 + (hydrophone4[1] - pinger_location[1])**2 + (hydrophone4[2] - pinger_location[2])**2 ) / 1500

print(time_1)
print(time_2)
print(time_3)
print(time_4)

0.014121457274500943
0.014180777286328293
0.014050820458448524
0.014140014144264496


In [33]:
distance_2 = (time_1 - time_2) * 1500
distance_3 = (time_1 - time_3) * 1500
distance_4 = (time_1 - time_4) * 1500

main_vector = [
    hydrophone2,
    hydrophone3,
    hydrophone4
]

distance_vector = [
    [distance_2],
    [distance_3],
    [distance_4]
]

main_vector = np.array(main_vector)
distance_vector = np.array(distance_vector)
inverse_main_vector = np.linalg.inv(main_vector)

result = np.matmul(inverse_main_vector, distance_vector)

print(main_vector)
print(distance_vector)
print(inverse_main_vector)
print(result)

[[-0.2   0.    0.15]
 [-0.25  0.15 -0.15]
 [ 0.2  -0.15  0.05]]
[[-0.08898002]
 [ 0.10595522]
 [-0.0278353 ]]
[[ -3.63636364  -5.45454545  -5.45454545]
 [ -4.24242424  -9.6969697  -16.36363636]
 [  1.81818182  -7.27272727  -7.27272727]]
[[-0.10254495]
 [-0.19446681]
 [-0.72992672]]
